# Heart Protocol Ethical Funding Configuration
# Supporting technology that serves love through community funding

github: # Will add when GitHub Sponsors approved
patreon: # Will add if/when Patreon account created
open_collective: # Will add when Open Collective set up
ko_fi: # Will add when Ko-fi account created
tidelift: # Not applicable for Heart Protocol
community_bridge: # Not applicable for Heart Protocol  
liberapay: # Will add if/when Liberapay account created
issuehunt: # Not applicable for Heart Protocol
otechie: # Not applicable for Heart Protocol
lfx_crowdfunding: # Not applicable for Heart Protocol
custom: # Will add custom donation links when available