version: '3.8'

services:
  monarch-bot:
    build: .
    container_name: monarch-bot
    restart: unless-stopped
    environment:
      - BLUESKY_HANDLE=${BLUESKY_HANDLE}
      - BLUESKY_APP_PASSWORD=${BLUESKY_APP_PASSWORD}
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - heart-protocol
    
  # Optional: Add monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - heart-protocol
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=heartprotocol
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - heart-protocol
    profiles:
      - monitoring

networks:
  heart-protocol:
    driver: bridge

volumes:
  grafana-data: